POST http://localhost:8000/auth/register HTTP/1.1
content-type: application/json

{
    "role":["Administrator"],
    "email":"fajarsoegi@gmail.com",
    "username": "fajarsoegi",
    "password": "fajarsoegi1901"
}