POST http://localhost:8000/api/corporation HTTP/1.1
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NzMxODUzNzEsImlkIjoiVVNSNzU5MjM4MTg1NSJ9.5ln9GxQ1_1Jd3WnI-KdsrSskm-MmxENmeioEyIZHOyQ

{
    "code":"3500",
    "name":"PT. SALIM IVOMAS PRATAMA",
    "description":"",
    "phone_number":"0213989832",
    "fax":"021321398",
    "sector":"Agricultur",
    "domain":"simp.co.id"
}