POST http://localhost:8000/auth/register HTTP/1.1
content-type: application/json

{
    "role":["Administrator1"],
    "application_id":"APP3879524866",
    "email":"example@email.com",
    "username": "sampleusername",
    "password": "samplepassword"
}