POST http://localhost:8000/api/user/USR7592381855/assign_roles HTTP/1.1
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NzMxODM2MzcsImlkIjoiVVNSNzU5MjM4MTg1NSJ9.9lchzc7nNKVv_dzajkocnfSDsvHfZpuLgBrPKcS9Wd4

{
    "role":["Administrator","Contributor","Editor","Subscriber"]
}