GET http://localhost:8000/v1/user/USR8432382036 HTTP/1.1
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NzMyNzM5NjEsImlkIjoiVVNSODQzMjM4MjAzNiJ9.TPrj0AfPqh87ANyNdnyM0J8zSViiJNDXUC73MHx5qqM